services:
  app:
    container_name: api_system_care_packeage
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: pnpm start:dev
    ports:
      - 4000:3000
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db_system_care_packeage
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '6000:5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local